language: python
os:
- linux
- osx
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install coveralls
script: nosetests --with-coverage --cover-package=taffmat
after_success: coveralls
deploy:
  provider: pypi
  user: mdrpypi
  password:
    secure: 8v1g9ScIbgasoWjlsuimA32v066w9ZwEqLjeXY1jUTArhy3WSyk4OTnCPMJ6ZanYqDVumYlVHCBzZZEXSolKViQF5AIS6qY1/qsbtph4Arg+QiC8/Wk4QNSdiK90N+k6clSQI/Jr4i8DuDKsIPqSiZgoEXgK58aauVDYgBWZbYg=
  on:
    all_branches: true
    tags: true
    repo: questrail/taffmat
