sudo: false
language: python
os:
  - linux
python:
  - '3.4'
  - '3.5'
  - '3.6'
addons:
  apt:
    packages:
      - pandoc
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: nosetests --with-coverage --cover-package=taffmat
after_success: coveralls
